{% set distro_version = "10.0" %}
{% set glibc_version = "2.39" %}
{% set kernel_headers_version = "6.12.0" %}
{% set build_number = "4" %}

{% set rpm_url = "https://dl.rockylinux.org/pub/rocky/" ~ distro_version ~ "/BaseOS/" ~ centos_machine ~ "/os/Packages" %}
{% set appstream_rpm_url = "https://dl.rockylinux.org/pub/rocky/" ~ distro_version ~ "/AppStream/" ~ centos_machine ~ "/os/Packages" %}
{% set crb_rpm_url = "https://dl.rockylinux.org/pub/rocky/" ~ distro_version ~ "/CRB/" ~ centos_machine ~ "/os/Packages" %}

package:
  name: linux-sysroot
  version: {{ glibc_version }}

source:
  # for calculating the hashes below, you can run `python update.py`
  # in the recipe folder (only `distro_version` needs to be set therein)
  # START source
  - folder: binary-glibc
    url: {{ rpm_url }}/g/glibc-2.39-46.el10_0.{{ centos_machine }}.rpm
    sha256: 76114979289031522976a9e42635865b211393b67d058d4285093f5b3131cb5e  # [cross_target_platform == "linux-64"]
    sha256: 106adc725be3149c6c3aa82b7557a491a22659b48cb7eb5d1a7623e6f3524ff6  # [cross_target_platform == "linux-aarch64"]
    sha256: 6506860f1442a74c3ff36fe96ff8be467cf7c8efbcf15fdbb32444f3b36d6af8  # [cross_target_platform == "linux-ppc64le"]
    sha256: 03f6b02b5dacc1be42d6be0ae001b644b26c2c7e59ca59480d95a5de42fbf04b  # [cross_target_platform == "linux-riscv64"]
    sha256: e3cb299c9b7aea905cf71246069a4ff8600b92c9155a1c25234f39836832bd08  # [cross_target_platform == "linux-s390x"]

  - folder: binary-glibc-all-langpacks
    url: {{ rpm_url }}/g/glibc-all-langpacks-2.39-46.el10_0.{{ centos_machine }}.rpm
    sha256: d1024a535893b1337f392d53d1aeb36af19668f3a0619b96888cc829584f3918  # [cross_target_platform == "linux-64"]
    sha256: 5234402bc8fb202a4ee97458b627f0916eee5f06470ccd1e4c3e16a82ddb8df6  # [cross_target_platform == "linux-aarch64"]
    sha256: 99d2259c44af7ef906d29bec1b14f026932e55af19d662e28935e24c1415c22a  # [cross_target_platform == "linux-ppc64le"]
    sha256: abe076903cb0bca575babf85078d6be4e4253fd1dd6bb1b632dc419f2eff20a7  # [cross_target_platform == "linux-riscv64"]
    sha256: dd8d16525c47efee2094239052d123f157ecb1c8c2c7d8136c4380d50a7be1c0  # [cross_target_platform == "linux-s390x"]

  - folder: binary-glibc-common
    url: {{ rpm_url }}/g/glibc-common-2.39-46.el10_0.{{ centos_machine }}.rpm
    sha256: 1c5077437476010b963e802a9570c1baf63f1bd48dbaca53303aa713a599b415  # [cross_target_platform == "linux-64"]
    sha256: 03f1360eb0bd3686223632d2280034fe1b7c9833992575d701a50b04918a67c9  # [cross_target_platform == "linux-aarch64"]
    sha256: 1769daca93eee16edf2125f335626e919b454c0e3d15482ed2134f25a4622e19  # [cross_target_platform == "linux-ppc64le"]
    sha256: eccbba86f69fb4e4031dc94446d660467783ebc9823db59af5c2868efe2a8029  # [cross_target_platform == "linux-riscv64"]
    sha256: 8ba0f13985812fa917eedb54e9c20f8668960f442bacd580401cfc4518bc7398  # [cross_target_platform == "linux-s390x"]

  - folder: binary-glibc-devel
    url: {{ appstream_rpm_url }}/g/glibc-devel-2.39-46.el10_0.{{ centos_machine }}.rpm
    sha256: ad8d9023e71a2ae3cebcdff9e5b22e47d63c500b3654e6a61a32ee83257f2919  # [cross_target_platform == "linux-64"]
    sha256: cfa928e01c68b6c831635491a44d3ea3e912b1b4c6938695aee0200545259b0a  # [cross_target_platform == "linux-aarch64"]
    sha256: 513e243ad64418e1d970b82ae07b8329d7dff2a11ac74886318805a7cebd61bf  # [cross_target_platform == "linux-ppc64le"]
    sha256: 67c2852e71b52bbc048e1fe5e34ef0d3afb8d63b41fc3377c6f0e6725e63ba0f  # [cross_target_platform == "linux-riscv64"]
    sha256: b368e47eb8d2b58806a2b6c01035609ff5fca8972303bf77cce0f7bf87b7b50b  # [cross_target_platform == "linux-s390x"]

  - folder: binary-glibc-gconv-extra
    url: {{ rpm_url }}/g/glibc-gconv-extra-2.39-46.el10_0.{{ centos_machine }}.rpm
    sha256: f155193e0200341b430f7029141a857666c0609a8623ceab6f03168b459a4baa  # [cross_target_platform == "linux-64"]
    sha256: 43debb646a34920e482c107947bd4b0167acc67ee3f7682a40a9c5e9e20f4dbd  # [cross_target_platform == "linux-aarch64"]
    sha256: 66c412c4820aad1bad8a789b94a481cf7652485b2c104acdadb5ae6f2c7c920c  # [cross_target_platform == "linux-ppc64le"]
    sha256: 1e4efb0603310165b5342c8e414a503db3959b51db822589ec78ad00fb2ee376  # [cross_target_platform == "linux-riscv64"]
    sha256: aad90e128192ee24664de387e08ab3372827b5bf4620f9712168170f2f32a4fc  # [cross_target_platform == "linux-s390x"]

  - folder: binary-glibc-static
    url: {{ crb_rpm_url }}/g/glibc-static-2.39-46.el10_0.{{ centos_machine }}.rpm
    sha256: f5cbde0cff3a11be47a8422d1474a143cd789fca2b5a5acdb088c501926cc751  # [cross_target_platform == "linux-64"]
    sha256: 4b0ce7aa3809ebc3eb7a82c1f2144a85ac45c3968216b633506f67d4b1af5e94  # [cross_target_platform == "linux-aarch64"]
    sha256: bd86c4ab42f6565260425f6466f9ce5377f7d1ad9d884cbc0047a235e44e8d9f  # [cross_target_platform == "linux-ppc64le"]
    sha256: 45942b1d933b9b861b9e48b7c988f0d7eb49fe563f1e16b3155a4dcaeebde96f  # [cross_target_platform == "linux-riscv64"]
    sha256: b6268d23db01f42ebac2ee905b083266fa5d465f47086b33accf6b8cad77ff49  # [cross_target_platform == "linux-s390x"]

  - folder: binary-kernel-headers
    url: {{ appstream_rpm_url }}/k/kernel-headers-6.12.0-55.41.1.el10_0.{{ centos_machine }}.rpm
    sha256: c0ae34bc9cda7169051a943ec547693b2a39c6ba48184a8028648c5f616511a7  # [cross_target_platform == "linux-64"]
    sha256: 66966a6dc361d11a4363112c547cbb85a82054ae3e16825e53aa3ef09dbcea26  # [cross_target_platform == "linux-aarch64"]
    sha256: d08ac4aa4a5e38a8fdca09d8e895421a1e9ea05d9d18171aa82a7f6a780d576c  # [cross_target_platform == "linux-ppc64le"]
    sha256: 1ef494d80276f24ae0a08210c5f96adb8221f43d7aacee53afb18c9b9042526d  # [cross_target_platform == "linux-riscv64"]
    sha256: 1bdca7a9db422a74c66a1ca6d7c043e74e1c9159300a023be43186847bb894ac  # [cross_target_platform == "linux-s390x"]
  # END source

build:
  number: {{ build_number }}

outputs:
  - name: kernel-headers_{{ cross_target_platform }}
    version: {{ kernel_headers_version }}
    script: build-kernel-headers.sh
    build:
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
    requirements:
      run_constrained:
        - sysroot_{{ cross_target_platform }} =={{ glibc_version }}
    test:
      commands:
        # the files below are just a sample of the full content
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/asm-generic/errno.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/asm/types.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/drm/drm.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/linux/fuse.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/sound/asound.h
        # ensure vendor templating worked correctly
        - test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/usr/include/linux/version.h

  - name: sysroot_{{ cross_target_platform }}
    script: build-sysroot.sh
    build:
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
      missing_dso_whitelist:
        - '*'
      track_features:
        - sysroot_{{ cross_target_platform }}_{{ glibc_version }}               # [with_features]
        - sysroot_{{ cross_target_platform }}_{{ glibc_version }}_feature_2     # [with_features]
        - sysroot_{{ cross_target_platform }}_{{ glibc_version }}_feature_3     # [with_features]
      run_exports:
        strong:
          - __glibc >={{ glibc_version }},<3.0.a0
    requirements:
      host:
        - tzdata
      run:
        - __glibc >={{ glibc_version }}     # [not with_features]
        - {{ pin_subpackage('kernel-headers_' ~ cross_target_platform, exact=True) }}
        - tzdata
    test:
      commands:
        # for conda-build sysroot detection
        - test -d $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/lib64
        - test ! -L $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/lib64
        # the files below are just a sample of the full content
        {% for path_fragment in ["lib", "lib64", "usr/lib", "usr/lib64"] %}
        # libraries & special objects
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/crt1.o
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libc.a
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libc.so.6
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libdl.a
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libm.a
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libm.so.6
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/Scrt1.o
        # ensure vendor templating worked correctly
        - test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/{{ path_fragment }}/libc.so.6
        {% endfor %}
        {% for path_fragment in [".", "usr"] %}
        # binaries
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/bin/ld.so
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/bin/ldd
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/sbin/ldconfig
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/sbin/iconvconfig
        {% endfor %}
        # headers
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/limits.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs-64.h   # [cross_target_platform == "linux-64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs.h      # [cross_target_platform != "linux-64"]
        # locale metadata
        - test -d $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/share/locale
        # absence of removed libraries
        - find "${PREFIX}" \( -name 'libnsl*' -o -path '*/rpcsvc/yp*' \) | { ! grep . ; }
        - find "${PREFIX}" \( -name 'libcrypt*' -o -name 'crypt.*' \) | { ! grep . ; }

about:
  home: https://dl.rockylinux.org/pub/rocky/{{ distro_version }}
  license: LGPL-2.0-or-later AND LGPL-2.0-or-later WITH exceptions AND GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  # license files are packaged with source
  summary: "(CDT) The GNU libc libraries and header files for the Linux kernel for use by glibc"
  description: |
        The glibc package contains standard libraries which are used by multiple
        programs on the system. In order to save disk space and memory, as well as to
        make upgrading easier, common system code is kept in one place and shared
        between programs. This particular package contains the most important sets of
        shared libraries: the standard C library and the standard math library.
        Without these two libraries, a Linux system will not function.

        Kernel-headers includes the C header files that specify the interface between
        the Linux kernel and userspace libraries and programs.  The header files
        define structures and constants that are needed for building most standard
        programs and are also needed for rebuilding the glibc package.

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - beckermr
