{% set rocky_version = "10.0" %}
{% set glibc_version = "2.39" %}
{% set kernel_headers_version = "6.12.0" %}
{% set build_number = "0" %}

{% set rpm_url = "https://download.rockylinux.org/vault/rocky/" ~ rocky_version ~ "/BaseOS/" ~ centos_machine ~ "/os/Packages" %}
{% set appstream_rpm_url = "https://download.rockylinux.org/vault/rocky/" ~ rocky_version ~ "/AppStream/" ~ centos_machine ~ "/os/Packages" %}
{% set devel_rpm_url = "https://download.rockylinux.org/vault/rocky/" ~ rocky_version ~ "/devel/" ~ centos_machine ~ "/os/Packages" %}

package:
  name: linux-sysroot
  version: {{ glibc_version }}

source:
  # for calculating the hashes below, you can run `python update.py`
  # in the recipe folder (after ensuring the versions in CBC are correct)
  # START source
  - folder: binary-glibc
    url: {{ rpm_url }}/g/glibc-2.39-46.el10_0.4.{{ centos_machine }}.rpm
    sha256: 868fea6054f0d28413cd5ecdb2b7df06772cabfe1c701a21e142ab9f0ab50ae5  # [cross_target_platform == "linux-64"]
    sha256: 9f7b3da58ea306aaa51a8c0fcdbcd8543b0e66204e596e52573ff3f9830b0235  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-glibc-all-langpacks
    url: {{ rpm_url }}/g/glibc-all-langpacks-2.39-46.el10_0.4.{{ centos_machine }}.rpm
    sha256: 9a4ed7f0af50307fb6ceda68d9bbb030e346e804de9b96d62951d5ad6530e3e7  # [cross_target_platform == "linux-64"]
    sha256: 36721bd7c5746c2bb6df2b85b9b65603815a6a14c4409262bf0b6bbcef96a2e3  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-glibc-common
    url: {{ rpm_url }}/g/glibc-common-2.39-46.el10_0.4.{{ centos_machine }}.rpm
    sha256: 0899e3f60843edb42b25c24f9c2d7533b6af277d0162bab6a82dd27e0e595b38  # [cross_target_platform == "linux-64"]
    sha256: f39a506253ae905927d3ebd1cb402226a142adce67b94fd43f3c3f2d2add7f2d  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-glibc-devel
    url: {{ appstream_rpm_url }}/g/glibc-devel-2.39-46.el10_0.4.{{ centos_machine }}.rpm
    sha256: a2fe5b0ef00713a0dad3d280e18485e9afcbdf889f3d95c23588c7536210023e  # [cross_target_platform == "linux-64"]
    sha256: a9cc5c31f9c9e933d9004f4a2760916d2d6366dd99ab8bf962e52c764952694f  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-glibc-gconv-extra
    url: {{ rpm_url }}/g/glibc-gconv-extra-2.39-46.el10_0.4.{{ centos_machine }}.rpm
    sha256: e19382ccabcf042fae957bc7571c9974615c04bfe2a0023c2a7c844e605fd6ce  # [cross_target_platform == "linux-64"]
    sha256: 34146e2abd2ea311a5a415c9691f7e3624fab2c1d2aaebf421355070d265d7e8  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-glibc-static
    url: {{ devel_rpm_url }}/g/glibc-static-2.39-46.el10_0.4.{{ centos_machine }}.rpm
    sha256: cd37e777b49acb85facab5290524879aa7c16f75aad587d8bec4c22ffc3334f1  # [cross_target_platform == "linux-64"]
    sha256: f7f7c3a2dfb15ad2675758f5671448c966493201eb546a832c7615272d9c5077  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-kernel-headers
    url: {{ appstream_rpm_url }}/k/kernel-headers-6.12.0-55.41.1.el10_0.{{ centos_machine }}.rpm
    sha256: c0ae34bc9cda7169051a943ec547693b2a39c6ba48184a8028648c5f616511a7  # [cross_target_platform == "linux-64"]
    sha256: 66966a6dc361d11a4363112c547cbb85a82054ae3e16825e53aa3ef09dbcea26  # [cross_target_platform == "linux-aarch64"]
  # END source

build:
  number: {{ build_number }}
  noarch: generic
  # This package builds cross targets so only need to run once.
  skip: True  # [not (linux)]

outputs:
  - name: kernel-headers_{{ cross_target_platform }}
    version: {{ kernel_headers_version }}
    script: build-kernel-headers.sh
    build:
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
    requirements:
      run_constrained:
        - sysroot_{{ cross_target_platform }} =={{ glibc_version }}
    test:
      commands:
        test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/usr/include/linux/version.h

  - name: sysroot_{{ cross_target_platform }}
    script: build-sysroot.sh
    build:
      missing_dso_whitelist:
        - '*'
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
      track_features:
        # this is two versions advanced from the default, so two features
        - sysroot_{{ cross_target_platform }}_{{ glibc_version }}
        - sysroot_{{ cross_target_platform }}_{{ glibc_version }}_2
      run_exports:
        strong:
          - __glibc >={{ glibc_version }},<3.0.a0
    requirements:
      host:
        - tzdata
        - __glibc >={{ glibc_version }}
      run:
        - {{ pin_subpackage('kernel-headers_' ~ cross_target_platform, exact=True) }}
        - tzdata
    test:
      commands:
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/lib64/libc.so.6
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/sbin/ldconfig
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/lib64/crt1.o
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/limits.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs-64.h  # [cross_target_platform == "linux-64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs.h
        - test -d $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/share/locale
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/bin/ldd
        - test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/usr/lib64/libc.so.6
        - find "${PREFIX}" \( -name 'libnsl*' -o -path '*/rpcsvc/yp*' \) | { ! grep . ; }
        - find "${PREFIX}" \( -name 'libcrypt*' -o -name 'crypt.*' \) | { ! grep . ; }

about:
  home: https://download.rockylinux.org/vault/rocky/{{ rocky_version }}
  license: LGPL-2.0-or-later AND LGPL-2.0-or-later WITH exceptions AND GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  # license files are packaged with source
  summary: "(CDT) The GNU libc libraries and header files for the Linux kernel for use by glibc"
  description: |
        The glibc package contains standard libraries which are used by multiple
        programs on the system. In order to save disk space and memory, as well as to
        make upgrading easier, common system code is kept in one place and shared
        between programs. This particular package contains the most important sets of
        shared libraries: the standard C library and the standard math library.
        Without these two libraries, a Linux system will not function.

        Kernel-headers includes the C header files that specify the interface between
        the Linux kernel and userspace libraries and programs.  The header files
        define structures and constants that are needed for building most standard
        programs and are also needed for rebuilding the glibc package.

extra:
  skip-lints:
    - missing_dev_url
    - missing_documentation
    - incorrect_license
    - host_section_needs_exact_pinnings
  recipe-maintainers:
    - isuruf
    - scopatz
    - beckermr
