{% set glibc_version = "2.35" %}
{% set kernel_headers_version = "5.15.0" %}
{% set build_number = 0 %}

package:
  name: linux-sysroot
  version: "{{ glibc_version }}"

source:
  # Refresh with `python update.py` from recipe/; see its version arguments.
  # START source
  - folder: binary-libc6
    fn: libc6.deb
    url: https://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.35-0ubuntu3.15_amd64.deb  # [cross_target_platform == "linux-64"]
    sha256: 79e35256227e16a607c154cdeb8d76ff12d20e31de286ea7fd9ad3b96fe0452d  # [cross_target_platform == "linux-64"]
    url: https://ports.ubuntu.com/ubuntu-ports/pool/main/g/glibc/libc6_2.35-0ubuntu3.15_arm64.deb  # [cross_target_platform == "linux-aarch64"]
    sha256: dd88cc85dcfbac19c0c9b606676b7b1b87f851d75afa5c830fc5ba1293a30833  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-libc6-dev
    fn: libc6-dev.deb
    url: https://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev_2.35-0ubuntu3.15_amd64.deb  # [cross_target_platform == "linux-64"]
    sha256: ce51ae233a9f800a040de2d0cd5983ef86f558c623b342c80942301d7f453f48  # [cross_target_platform == "linux-64"]
    url: https://ports.ubuntu.com/ubuntu-ports/pool/main/g/glibc/libc6-dev_2.35-0ubuntu3.15_arm64.deb  # [cross_target_platform == "linux-aarch64"]
    sha256: e1da77e87451ca8f41b2757fe274bca357fd5f7498afe47c05360681d0727bae  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-libc-bin
    fn: libc-bin.deb
    url: https://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc-bin_2.35-0ubuntu3.15_amd64.deb  # [cross_target_platform == "linux-64"]
    sha256: 3dd58c112ada83860b00b8f0fdb5ff8923f64f4f14b932648cc19e31b0981fca  # [cross_target_platform == "linux-64"]
    url: https://ports.ubuntu.com/ubuntu-ports/pool/main/g/glibc/libc-bin_2.35-0ubuntu3.15_arm64.deb  # [cross_target_platform == "linux-aarch64"]
    sha256: e222d3db00057f6c8c7ce1e9c1668d687d34f54d551938af4a4a4ecc24c84bc3  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-locales
    fn: locales.deb
    url: https://archive.ubuntu.com/ubuntu/pool/main/g/glibc/locales_2.35-0ubuntu3.15_all.deb  # [cross_target_platform == "linux-64"]
    sha256: 9094f7e6c619a385b05995e0d71d12122368fd3d2f0526a5298a9bd392a94b64  # [cross_target_platform == "linux-64"]
    url: https://ports.ubuntu.com/ubuntu-ports/pool/main/g/glibc/locales_2.35-0ubuntu3.15_all.deb  # [cross_target_platform == "linux-aarch64"]
    sha256: 9094f7e6c619a385b05995e0d71d12122368fd3d2f0526a5298a9bd392a94b64  # [cross_target_platform == "linux-aarch64"]

  - folder: binary-linux-libc-dev
    fn: linux-libc-dev.deb
    url: https://archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.15.0-191.201_amd64.deb  # [cross_target_platform == "linux-64"]
    sha256: 716aff7595cee9b427f23228e40829df437a415055e3e9867a76c2d59f3f1b75  # [cross_target_platform == "linux-64"]
    url: https://ports.ubuntu.com/ubuntu-ports/pool/main/l/linux/linux-libc-dev_5.15.0-191.201_arm64.deb  # [cross_target_platform == "linux-aarch64"]
    sha256: 83417011bd0932781e281057669ad424e45944e2cdc9d5e2fab2c8e6ee29cd16  # [cross_target_platform == "linux-aarch64"]
  # END source

build:
  number: {{ build_number }}

outputs:
  - name: kernel-headers_{{ cross_target_platform }}
    version: "{{ kernel_headers_version }}"
    script: build-kernel-headers.sh
    build:
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
    requirements:
      build:
        - libarchive
      run_constrained:
        - sysroot_{{ cross_target_platform }} =={{ glibc_version }}
    about:
      home: https://www.kernel.org/
      summary: Linux UAPI headers from Ubuntu Jammy for the Conda compiler sysroot
      license: GPL-2.0-only WITH Linux-syscall-note
      license_file:
        - binary-linux-libc-dev/root/usr/share/doc/linux-libc-dev/copyright
        - licenses/GPL-2.0.txt
        - licenses/Linux-syscall-note.txt
    test:
      commands:
        # the files below are just a sample of the full content
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/asm-generic/errno.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/asm/types.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/drm/drm.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/linux/fuse.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/sound/asound.h
        # ensure vendor templating worked correctly
        - test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/usr/include/linux/version.h

  - name: sysroot_{{ cross_target_platform }}
    script: build-sysroot.sh
    build:
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
      missing_dso_whitelist:
        - '*'
      track_features:
        - sysroot_{{ cross_target_platform }}_{{ glibc_version }}               # [with_features]
        - sysroot_{{ cross_target_platform }}_{{ glibc_version }}_feature_2     # [with_features]
        - sysroot_{{ cross_target_platform }}_{{ glibc_version }}_feature_3     # [with_features]
      run_exports:
        strong:
          - __glibc >={{ glibc_version }},<3.0.a0
    requirements:
      build:
        - libarchive
      host:
        - tzdata
      run:
        - __glibc >={{ glibc_version }}     # [not with_features]
        - {{ pin_subpackage('kernel-headers_' ~ cross_target_platform, exact=True) }}
        - tzdata
    about:
      home: https://launchpad.net/ubuntu/jammy/+source/glibc
      summary: Ubuntu Jammy glibc 2.35 libraries and headers for the Conda compiler sysroot
      license: LGPL-2.1-or-later AND GPL-2.0-or-later
      license_family: GPL
      license_file:
        - binary-libc6/root/usr/share/doc/libc6/copyright
        - licenses/GPL-2.0.txt
        - licenses/LGPL-2.1.txt
    test:
      requires:
        - gcc_linux-64 11.4.0  # [cross_target_platform == "linux-64"]
        - gxx_linux-64 11.4.0  # [cross_target_platform == "linux-64"]
      files:
        - test-sysroot.sh
        - test-sysroot.c
        - test-sysroot.cpp
      commands:
        - bash test-sysroot.sh  # [cross_target_platform == "linux-64"]
        # for conda-build sysroot detection
        - test -d $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/lib64
        - test ! -L $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/lib64
        # the files below are just a sample of the full content
        {% for path_fragment in ["lib", "lib64", "usr/lib", "usr/lib64"] %}
        # libraries & special objects
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/crt1.o
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libc.a
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libc.so.6
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libdl.a
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libm.a
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/libm.so.6
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/Scrt1.o
        # ensure vendor templating worked correctly
        - test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/{{ path_fragment }}/libc.so.6
        {% endfor %}
        {% for path_fragment in [".", "usr"] %}
        # binaries
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/bin/ld.so
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/bin/ldd
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/sbin/ldconfig
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/{{ path_fragment }}/sbin/iconvconfig
        {% endfor %}
        # headers
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/limits.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs-64.h   # [cross_target_platform == "linux-64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs.h      # [cross_target_platform != "linux-64"]
        # locale metadata
        - test -d $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/share/locale
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/share/locale/locale.alias
        - test "$(readlink "$PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/share/locale/locale.alias")" = ../../../etc/locale.alias
        # absence of removed libraries
        - find "${PREFIX}" \( -name 'libnsl*' -o -path '*/rpcsvc/yp*' \) | { ! grep . ; }
        - find "${PREFIX}" \( -name 'libcrypt*' -o -name 'crypt.*' \) | { ! grep . ; }

about:
  home: https://launchpad.net/ubuntu/jammy/+source/glibc
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_family: GPL
  license_file:
    - binary-libc6/root/usr/share/doc/libc6/copyright
    - binary-linux-libc-dev/root/usr/share/doc/linux-libc-dev/copyright
    - licenses/GPL-2.0.txt
    - licenses/LGPL-2.1.txt
    - licenses/Linux-syscall-note.txt
  summary: "(CDT) The GNU libc libraries and header files for the Linux kernel for use by glibc"
  description: |
        The glibc package contains standard libraries which are used by multiple
        programs on the system. In order to save disk space and memory, as well as to
        make upgrading easier, common system code is kept in one place and shared
        between programs. This particular package contains the most important sets of
        shared libraries: the standard C library and the standard math library.
        Without these two libraries, a Linux system will not function.

        Kernel-headers includes the C header files that specify the interface between
        the Linux kernel and userspace libraries and programs.  The header files
        define structures and constants that are needed for building most standard
        programs and are also needed for rebuilding the glibc package.

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - beckermr
